### ISSUE TITLE
Debugging a 400 bad request and clarifying the access code

### ISSUE THREAD

**Issue by mmikitka** [jborchma/qtrade#23]
Hello Jan. First, thanks for creating this package, and I look forward to using it.

I was not able to obtain an access token. Can you please clarify the initialization workflow and where the values are sourced from? I did the following:

1. Created a Personal App at https://login.questrade.com/APIAccess/UserApps.aspx
2. Clicked the "+ New device" link to create a new manually authorized device
3. Clicked the "Generate token" link to create a new token (call it MY_TOKEN=1234567890ABCDEFG)
4. Passed this token into qtrade.Questrade(access_code=MY_TOKEN)

I then get the following traceback
```
Traceback (most recent call last):
  File "./options.py", line 11, in <module>
    qtrade = Questrade(access_code=access_code)
  File "/app/qtrade/qtrade/questrade.py", line 38, in __init__
    self.get_access_token()
  File "/app/qtrade/qtrade/questrade.py", line 83, in get_access_token
    data.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://login.questrade.com/oauth2/token?grant_type=refresh_token&refresh_token=1234567890ABCDEFG
```

**Comment by jborchma** [comment]
Sorry for only getting back to you now, but I was away all of last week and am just catching up. 

This is weird, are you sure you're using the right token? I just recreated my own token and I was able to initialize the class just fine. Did you save the token as a string?

**Comment by mmikitka** [comment]
Thanks for your help Jan.

Can you confirm that you followed the same process for obtaining a token as myself?

Also, I'm using the master HEAD commit `3fb89b620ec2a12a4eea9becfed87ea782107b2e`

**Comment by mmikitka** [comment]
I tried again using the steps outlined in the beginning and I still see the same behaviour. I also confirmed that the token is a string.

**Comment by jborchma** [comment]
Ok, that's so odd, I have not been able to reproduce this. Can you please post the complete code (with a fake token, of course)?

**Comment by jborchma** [comment]
I ran

```python
token="hunter2"
qt = Questrade(access_code=token)
```

and it worked fine.

**Comment by mmikitka** [comment]
Found the problem: since I'm iterating quickly on my app, the first invocation was successful, which generates `access_token.yml`, but subsequent fail. So, I'm currently doing the following:

1. Generate access code through Questrade web UI
2. Call script with `qt = Questrade(access_token=token)`. This saves `access_token.yml` to the working directory
3. Subsequent calls (within 1800 seconds) of the script use the `token_yaml` parameter

However, now I'm seeing a 403 error when I follow one of your examples to lookup the current price of AAPL:
```
$ docker run --rm -it -v /home/mmikitka/src/investit/questrade:/app --user 1000:1000 --env-file=env questrade ./options.py
Loading access token from yaml...
Validating access token...
Getting ticker data...
Starting new HTTPS connection (1): api05.iq.questrade.com:443
https://api05.iq.questrade.com:443 "GET /v1/symbols?names=AAPL HTTP/1.1" 403 64
Traceback (most recent call last):
  File "./options.py", line 20, in <module>
    aapl = qtrade.get_quote('AAPL')
  File "/app/qtrade/qtrade/questrade.py", line 334, in get_quote
    info = self.ticker_information(tickers)
  File "/app/qtrade/qtrade/questrade.py", line 304, in ticker_information
    response = self._send_message('get', 'symbols', params=payload)
  File "/app/qtrade/qtrade/questrade.py", line 67, in _send_message
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api05.iq.questrade.com/v1/symbols?names=AAPL
```

here is my code

```
#!/usr/bin/env python3

import logging
import os
import sys

sys.path.append('/app/qtrade')
from qtrade import Questrade

logger = logging.getLogger()
handler = logging.StreamHandler()
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)

access_code = os.environ['QUESTRADE_API_TOKEN']

#qtrade = Questrade(access_code=access_code)
qtrade = Questrade(token_yaml='/app/access_token.yml')

aapl = qtrade.get_quote('AAPL')
print(aapl)
```

Thanks for your help.

**Comment by mmikitka** [comment]
Found the problem: I had to enable the "Retrieve balances, positions, orders and executions" OAuth scope to call the `v1/symbols` endpoint, which seems like a scoping error. I thought that "Retrieve delayed and real-time market data" would be sufficient.

**Comment by mmikitka** [comment]
I'm going to notify Questrade about my experience as I would rather not expose the account-related scope.

**Comment by jborchma** [comment]
Interesting, I didn't know about this. Glad you were able to figure it out!
