### ISSUE TITLE
submit ordre

### ISSUE THREAD

**Issue by mhirimohamed** [jborchma/qtrade#25]
the submit_order is not working with me: 
the http status code is 400 (bad request). Can you please give us an example ? I am using a partner app (Medved Trader)

**Comment by jborchma** [comment]
Hey! Thanks for letting me know. Can you post the trace, by any chance? (Minus any potential personal information, of course)

**Comment by mhirimohamed** [comment]
Can you please give us an example ?  with personal app we are not authorized to submit order so we need to use a partner apps ? which one is better how can we use it to submit order?  Can you please help it is URGENT.

**Comment by jborchma** [comment]
Hmmm, so in principle this should work:

```python
acct_id = 1234567
order_dict = {'accountNumber': 1234567,
        'symbolId': 3925293,
        'quantity': 1,
        'icebergQuantity': 1,
        'limitPrice': 57.58,
        'isAllOrNone': True,
        'isAnonymous': False,
        'orderType': 'Limit',
        'timeInForce': 'GoodTillCanceled',
        'action': 'Buy',
        'primaryRoute': 'AUTO',
        'secondaryRoute': 'AUTO'}

submission_response = qtrade.submit_order(acct_id,  order_dict)
```

I can't test this though since I don't have access to any partner apps that would be allowed to post orders.
