### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by topdeveloper424** [jborchma/qtrade#37]
![image](https://user-images.githubusercontent.com/40516126/78624432-92e21780-7857-11ea-89d8-c03a0168271f.png)

**Comment by topdeveloper424** [comment]
i got this error.  I just used this code
```
from qtrade import Questrade
qtrade = Questrade(access_code='<refresh_token>')
qtrade.get_access_token()
```

**Comment by jborchma** [comment]
Hmm, I will take a look to see if I can reproduce this.

**Comment by topdeveloper424** [comment]
Thank you
I am not sure if this module is wrong or Questrade is not serving

**Comment by topdeveloper424** [comment]
questrade api is working now ?

**Comment by jborchma** [comment]
So, I can't actually reproduce your error. The code works fine for me. Do you still have the issue?

**Comment by topdeveloper424** [comment]
yes. i still have the issue.  it is my API issue ?

**Comment by jborchma** [comment]
I am going to close this since I can't reproduce this and it seems to me this must be a local issue on your side.
