### ISSUE TITLE
"400 Client Error: Bad Request for url" when using "get_historical_data"

### ISSUE THREAD

**Issue by r-luo** [jborchma/qtrade#41]
Environment: conda python==3.8 environment with `qtrade` and `ipython` installed

Issue:
`'OneDay'` works with `get_historical_data`: 
```python
uvxy = q.get_historical_data('UVXY', '2019-07-01', '2019-07-02', 'OneDay')
```
but changing `'OneDay'` to `'OneHour'` causes error:
```python
>>> uvxy = q.get_historical_data('UVXY', '2019-07-01', '2019-07-02', 'OneHour')                                                 
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-22-a0637f02abb7> in <module>
----> 1 uvxy = q.get_historical_data('UVXY', '2019-07-01', '2019-07-02', 'OneHour')

~/Documents/projects/qtrade/qtrade/questrade.py in get_historical_data(self, ticker, start_date, end_date, interval)
    448         )
    449 
--> 450         response = self._send_message(
    451             "get", "markets/candles/" + str(ids), params=payload
    452         )

~/Documents/projects/qtrade/qtrade/questrade.py in _send_message(self, method, endpoint, params, data, json)
     83             method, url, params=params, data=data, json=json, timeout=30
     84         )
---> 85         resp.raise_for_status()
     86         return resp.json()
     87 

~/anaconda3/envs/qtrade/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    939 
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 
    943     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://api06.iq.questrade.com/v1/markets/candles/22992135?startTime=2019-07-01T00%3A00%3A00-05%3A00&endTime=2019-07-02T00%3A00%3A00-05%3A00&interval=OneHour
```

**Comment by jborchma** [comment]
Hmm, that is so odd. I will take a look tonight.

**Comment by jborchma** [comment]
So I can reproduce this as well. From testing it seems anything below `OneDay` is not working. [Here](https://www.questrade.com/api/documentation/rest-operations/enumerations/enumerations#historical-data-granularity) is the list of values that should be working. Given that lower granularity is working, this seems to me to be an API issue.

**Comment by r-luo** [comment]
Does it depend on what type of account you have? There's a premium option where you can get order book level information...

**Comment by jborchma** [comment]
Hmm, it definitely worked when I added it originally. I contacted support and will report back what I hear.

**Comment by Surohitt** [comment]
Hey, I was wondering if I could get access to make a PR to add some error handling for invalid intervals for future users? Took me longer than I'd like to admit before I found this issue 😅

**Comment by jborchma** [comment]
> Hey, I was wondering if I could get access to make a PR to add some error handling for invalid intervals for future users? Took me longer than I'd like to admit before I found this issue 😅

Hey! You don't need access to submit a PR. You can fork the repo and then submit a PR from your fork. I'd be happy to review and would love some contribution for better error messages!

**Comment by jborchma** [comment]
Fixed [here](https://github.com/jborchma/qtrade/pull/80). Thank you @Surohitt!
