### ISSUE TITLE
Suggestion: get account balance feature

### ISSUE THREAD

**Issue by eshinhw** [jborchma/qtrade#60]
Hi, I've enjoyed using your Questrade wrapper to perform analytic works on my accounts at Questrade. Just one suggestion, I hope there's a method which retrieves account balance data such as cash amount, total equity, and total market value by currencies. I figured in my own way to retrieve my balance data like below, but having this feature officially on your wrapper would be quite useful.

![image](https://user-images.githubusercontent.com/41933169/113016327-5f755880-914c-11eb-96a9-cf9f33f522e7.png)

(^ Not sure if this is a safe and right way to get the data from API, but it works fine with me so far)

Thanks!

**Comment by jborchma** [comment]
I think that's a great suggestion. I will look into this in the next little while and will aim to have this in the next release. Thank you very much for the suggestion.

**Comment by jborchma** [comment]
Done. I want to move my CICD pipeline over to GH actions as part of the next release, but master now has the new method.
