### ISSUE TITLE
How to place a new order using questrade api?

### ISSUE THREAD

**Issue by marvelmaester** [jborchma/qtrade#63]
Hi Jan, Is it possible to place a new order using code? I only see a provision to retrieve existing orders using the questrade api, it is mentioned in the following Questrade documentation - https://www.questrade.com/api/documentation/rest-operations/account-calls/accounts-id-orders.

But is it also possible to create a new order using questrade api? Looking forward to your response. Thank you.

**Comment by jborchma** [comment]
Hey! Sadly, as far as I'm aware, as a normal user of the API you cannot place orders through the questrade API. I even implemented the method for it, but you'll get back an error code for it. I'll close the issue because there is sadly nothing I can do :(

**Comment by marvelmaester** [comment]
Thank you Jan. Do you know if IB api allows us to place orders on TSX stocks. I heard it only allows on US based stocks.
