### ISSUE TITLE
retrieve account executions

### ISSUE THREAD

**Issue by John9909** [jborchma/qtrade#81]
thanks to all contributors for qtrade, which works well for me. 

The ability to get the latest execution would be a great addition (unless already available and i am not aware of).
In particular, that info is required to compute intra-day PnL. 

https://www.questrade.com/api/documentation/rest-operations/account-calls/accounts-id-executions

Best

**Comment by jborchma** [comment]
Thank you so much for the suggestion! I added the method in the new version. Please let me know if I overlooked any bugs!

**Comment by John9909** [comment]
that was very fast response, will be trying very shortly, thanks very much!

**Comment by John9909** [comment]
hi there, this week i tried get_account_executions( ) and it all worked well. 

Btw i noticed that for get_account_activities( ):
 if the initial date is more than 30 days before today, I receive en error (as opposed to returning 30 days' worth of data, as get_account_executions( )  does). 

Best
